name: Deploy AI Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Increased timeout for model downloads

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10  # Using 3.10 for better compatibility
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev libgomp1 ffmpeg libsm6 libxext6

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.cache/torch
          ~/.cache/huggingface
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt --no-cache-dir
        pip install --force-reinstall "huggingface-hub==0.22.2"  # Ensure correct version

    - name: Run application
      run: |
        python app.py
