name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        pip install flask frozen-flask transformers
        pip freeze > requirements.txt  # Optional: creates a requirements file
        
    - name: Build static site
      run: |
        python -c "from flask_frozen import Freezer; from app import app; freezer = Freezer(app); freezer.freeze()"
        # Or if you have a specific build script:
        # python build.py
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
